# Generated by Django 5.1.3 on 2025-05-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender/')),
                ('palabra', models.CharField(max_length=100)),
                ('audio_kichwa', models.FileField(blank=True, null=True, upload_to='audios_kichwa/')),
            ],
        ),
    ]
