# Generated by Django 5.1.3 on 2025-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0002_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender_Meses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_mes', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_meses/')),
                ('palabra_mes', models.CharField(max_length=100)),
                ('audio_kichwa_mes', models.FileField(blank=True, null=True, upload_to='audios_kichwa_meses/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Aprender',
            new_name='Aprender_Objetos',
        ),
        migrations.RenameField(
            model_name='aprender_objetos',
            old_name='audio_kichwa',
            new_name='audio_kichwa_obj',
        ),
        migrations.RenameField(
            model_name='aprender_objetos',
            old_name='imagen',
            new_name='imagen_obj',
        ),
        migrations.RenameField(
            model_name='aprender_objetos',
            old_name='palabra',
            new_name='palabra_obj',
        ),
    ]
