# Generated by Django 5.1.3 on 2025-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0003_aprender_meses_rename_aprender_aprender_objetos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprender_objetos',
            name='audio_kichwa_obj',
            field=models.FileField(blank=True, null=True, upload_to='audios_kichwa_objetos/'),
        ),
        migrations.AlterField(
            model_name='aprender_objetos',
            name='imagen_obj',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_objetos/'),
        ),
    ]
