# Generated by Django 4.1.13 on 2025-06-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0004_alter_aprender_objetos_audio_kichwa_obj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender_Numeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_num', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_numeros/')),
                ('palabra_num', models.CharField(max_length=100)),
                ('audio_kichwa_num', models.FileField(blank=True, null=True, upload_to='audios_kichwa_numeros/')),
            ],
        ),
    ]
