# Generated by Django 4.1.13 on 2025-06-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0005_aprender_numeros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender_Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_dia', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_dia/')),
                ('palabra_dia', models.CharField(max_length=100)),
                ('audio_kichwa_dia', models.FileField(blank=True, null=True, upload_to='audios_kichwa_dia/')),
            ],
        ),
    ]
