# Generated by Django 4.1.13 on 2025-06-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0006_aprender_dias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender_Saludos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_sal', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_saludos/')),
                ('palabra_sal', models.CharField(max_length=100)),
                ('audio_kichwa_sal', models.FileField(blank=True, null=True, upload_to='audios_kichwa_saludos/')),
            ],
        ),
    ]
