# Generated by Django 4.1.13 on 2025-06-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0007_aprender_saludos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender_Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_ani', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_animales/')),
                ('palabra_ani', models.CharField(max_length=100)),
                ('audio_kichwa_ani', models.FileField(blank=True, null=True, upload_to='audios_kichwa_animales/')),
            ],
        ),
    ]
