# Generated by Django 4.1.13 on 2025-06-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0008_aprender_animales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender_Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_col', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_colores/')),
                ('palabra_col', models.CharField(max_length=100)),
                ('audio_kichwa_col', models.FileField(blank=True, null=True, upload_to='audios_kichwa_colores/')),
            ],
        ),
    ]
