# Generated by Django 4.1.13 on 2025-06-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0010_aprender_cuerpo_humano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender_Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_par', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_parentesco/')),
                ('palabra_par', models.CharField(max_length=100)),
                ('audio_kichwa_par', models.FileField(blank=True, null=True, upload_to='audios_kichwa_parentesco/')),
            ],
        ),
    ]
