# Generated by Django 4.1.13 on 2025-06-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0011_aprender_parentesco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender_Elemento_Naturaleza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_ele', models.ImageField(blank=True, null=True, upload_to='imagenes_aprender_elementos_naturaleza/')),
                ('palabra_ele', models.CharField(max_length=100)),
                ('audio_kichwa_ele', models.FileField(blank=True, null=True, upload_to='audios_kichwa_elementos_naturaleza/')),
            ],
        ),
    ]
