# Generated by Django 4.1.13 on 2025-06-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0012_aprender_elemento_naturaleza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_est', models.CharField(max_length=100)),
                ('apellidos_est', models.CharField(max_length=100)),
                ('cedula_est', models.CharField(max_length=10, unique=True)),
                ('genero_est', models.CharField(max_length=20)),
                ('nivel_escolar_est', models.CharField(max_length=50)),
                ('estado_est', models.CharField(max_length=10)),
                ('fecha_registro_est', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion_est', models.DateField(auto_now=True)),
            ],
        ),
    ]
