# Generated by Django 4.1.13 on 2025-06-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0013_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='apellidos',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='cedula',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='nombres',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
