# Generated by Django 4.1.13 on 2025-06-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0014_profesor_apellidos_profesor_cedula_profesor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profesor/'),
        ),
    ]
