# Generated by Django 4.1.13 on 2025-06-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0017_resultado_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_actualizacion_est',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_registro_est',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
