# Generated by Django 4.1.13 on 2025-06-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0018_alter_estudiante_fecha_actualizacion_est_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='nivel_escolar_eva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
