# Generated by Django 4.1.13 on 2025-06-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0019_evaluacion_nivel_escolar_eva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante_Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_est_ter', models.CharField(max_length=100)),
                ('apellidos_est_ter', models.CharField(max_length=100)),
                ('cedula_est_ter', models.CharField(max_length=10, unique=True)),
                ('genero_est_ter', models.CharField(max_length=20)),
                ('nivel_escolar_est_ter', models.CharField(max_length=50)),
                ('estado_est_ter', models.CharField(max_length=10)),
                ('fecha_registro_est_ter', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_est_ter', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion_Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_eva_ter', models.CharField(max_length=200)),
                ('descripcion_eva_ter', models.TextField()),
                ('nivel_escolar_eva_ter', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_eva_ter', models.BooleanField(default=True)),
                ('tipo_aprendizaje_eva_ter', models.TextField()),
                ('fecha_creacion_eva_ter', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_eva_ter', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Estudiante_Cuarto',
        ),
        migrations.RenameModel(
            old_name='Evaluacion',
            new_name='Evaluacion_Cuarto',
        ),
        migrations.RenameModel(
            old_name='Resultado_Evaluacion',
            new_name='Resultado_Evaluacion_Cuarto',
        ),
        migrations.RenameField(
            model_name='estudiante_cuarto',
            old_name='apellidos_est',
            new_name='apellidos_est_cua',
        ),
        migrations.RenameField(
            model_name='estudiante_cuarto',
            old_name='cedula_est',
            new_name='cedula_est_cua',
        ),
        migrations.RenameField(
            model_name='estudiante_cuarto',
            old_name='estado_est',
            new_name='estado_est_cua',
        ),
        migrations.RenameField(
            model_name='estudiante_cuarto',
            old_name='fecha_actualizacion_est',
            new_name='fecha_actualizacion_est_cua',
        ),
        migrations.RenameField(
            model_name='estudiante_cuarto',
            old_name='fecha_registro_est',
            new_name='fecha_registro_est_cua',
        ),
        migrations.RenameField(
            model_name='estudiante_cuarto',
            old_name='genero_est',
            new_name='genero_est_cua',
        ),
        migrations.RenameField(
            model_name='estudiante_cuarto',
            old_name='nivel_escolar_est',
            new_name='nivel_escolar_est_cua',
        ),
        migrations.RenameField(
            model_name='estudiante_cuarto',
            old_name='nombres_est',
            new_name='nombres_est_cua',
        ),
        migrations.RenameField(
            model_name='evaluacion_cuarto',
            old_name='descripcion_eva',
            new_name='descripcion_eva_cua',
        ),
        migrations.RenameField(
            model_name='evaluacion_cuarto',
            old_name='estado_eva',
            new_name='estado_eva_cua',
        ),
        migrations.RenameField(
            model_name='evaluacion_cuarto',
            old_name='fecha_actualizacion_eva',
            new_name='fecha_actualizacion_eva_cua',
        ),
        migrations.RenameField(
            model_name='evaluacion_cuarto',
            old_name='fecha_creacion_eva',
            new_name='fecha_creacion_eva_cua',
        ),
        migrations.RenameField(
            model_name='evaluacion_cuarto',
            old_name='nivel_escolar_eva',
            new_name='nivel_escolar_eva_cua',
        ),
        migrations.RenameField(
            model_name='evaluacion_cuarto',
            old_name='tipo_aprendizaje_eva',
            new_name='tipo_aprendizaje_eva_cua',
        ),
        migrations.RenameField(
            model_name='evaluacion_cuarto',
            old_name='titulo_eva',
            new_name='titulo_eva_cua',
        ),
        migrations.RenameField(
            model_name='resultado_evaluacion_cuarto',
            old_name='fecha_res',
            new_name='fecha_res_cua',
        ),
        migrations.RenameField(
            model_name='resultado_evaluacion_cuarto',
            old_name='fk_estudiante',
            new_name='fk_estudiante_cua',
        ),
        migrations.RenameField(
            model_name='resultado_evaluacion_cuarto',
            old_name='fk_evaluacion',
            new_name='fk_evaluacion_cua',
        ),
        migrations.RenameField(
            model_name='resultado_evaluacion_cuarto',
            old_name='nota_res',
            new_name='nota_res_cua',
        ),
        migrations.CreateModel(
            name='Resultado_Evaluacion_Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_res_ter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_res_ter', models.DateTimeField(auto_now_add=True)),
                ('fk_estudiante_ter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulos.estudiante_tercero')),
                ('fk_evaluacion_ter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulos.evaluacion_tercero')),
            ],
        ),
    ]
