# Generated by Django 4.1.13 on 2025-07-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0020_estudiante_tercero_evaluacion_tercero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
