# Generated by Django 4.1.13 on 2025-07-31 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulos', '0021_profesor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion_cuarto',
            name='profesor',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='Modulos.profesor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion_tercero',
            name='profesor',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='Modulos.profesor'),
            preserve_default=False,
        ),
    ]
